[versions] # Ordered by alphabet
accompanistPermissions = "0.34.0"
agp = "8.6.1"
android-compileSdk = "35"
android-minSdk = "24"
android-targetSdk = "35"
androidx-activityCompose = "1.10.1"
androidx-appcompat = "1.7.0"
androidx-constraintlayout = "2.2.0"
androidx-core-ktx = "1.15.0"
androidx-espresso-core = "3.6.1"
androidx-lifecycle = "2.8.3"
androidx-material = "1.12.0"
androidx-test-junit = "1.2.1"
coil3 = "3.0.0-rc02"
compose-plugin = "1.7.0"
firebase = "2.1.0"
firebaseBom = "33.15.0"
firebaseMessaging = "24.1.0"
flexibleBottomsheetMaterial3 = "0.1.5"
google_services_version = "4.4.2"
junit = "4.13.2"
koin = "4.0.0"
kotlin = "2.2.0"
kotlinSerialization = "1.7.3"
kotlinx-coroutines = "1.9.0"
kotlinxDatetime = "0.6.0"
ksp = "2.2.0-2.0.2"
ktor = "3.0.0"
multiplatformSettings = "1.0.0"
navigationCompose = "2.8.0-alpha10"
passage = "1.4.0"
peekabooUi = "0.5.2"
peekabooImagePicker = "0.5.2"
pullrefresh = "1.3.0"
reveal = "3.1.1"
room = "2.7.0-alpha11"
sqlite = "2.5.0-alpha11"
uiBackhandler = "1.8.1"
xicon_pack_z = "1.1.1"
zoomable = "2.8.1"

[libraries] # Ordered by alphabet
accompanist-permissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core-ktx" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidx-espresso-core" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-material = { group = "com.google.android.material", name = "material", version.ref = "androidx-material" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
androidx-test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-junit" }

coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coil3" }
coil-compose-core = { module = "io.coil-kt.coil3:coil-compose-core", version.ref = "coil3" }
coil-mp = { module = "io.coil-kt.coil3:coil", version.ref = "coil3" }
coil-network-ktor2 = { module = "io.coil-kt.coil3:coil-network-ktor2", version.ref = "coil3" }
coil-network-ktor3 = { module = "io.coil-kt.coil3:coil-network-ktor3", version.ref = "coil3" }

com-google-firebase-firebase-auth = { module = "com.google.firebase:firebase-auth" }
com-google-firebase-firebase-firestore = { module = "com.google.firebase:firebase-firestore" }
com-google-firebase-firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
com-google-firebase-firebase-storage = { module = "com.google.firebase:firebase-storage" }

firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
firebase-auth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-firestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebase-messaging = { module = "dev.gitlive:firebase-messaging", version.ref = "firebase" }
firebase-storage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase" }

flexible-bottomsheet-material3 = { module = "com.github.skydoves:flexible-bottomsheet-material3", version.ref = "flexibleBottomsheetMaterial3" }

jetbrains-compose-navigation = { group = "org.jetbrains.androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

junit = { group = "junit", name = "junit", version.ref = "junit" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }

kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

ktor-client-auth = { module = "io.ktor:ktor-client-auth", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }

kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinSerialization" }

maplibre-compose = { module = "dev.sargunv.maplibre-compose:maplibre-compose", version = "0.6.0" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }

passage = { module = "io.github.tweener:passage", version.ref = "passage" }
peekaboo-image-picker = { module = "io.github.onseok:peekaboo-image-picker", version.ref = "peekabooImagePicker" }
peekaboo-ui = { module = "io.github.onseok:peekaboo-ui", version.ref = "peekabooUi" }
pullrefresh = { module = "dev.materii.pullrefresh:pullrefresh", version.ref = "pullrefresh" }

reveal-core = { module = "com.svenjacobs.reveal:reveal-core", version.ref = "reveal" }
reveal-shapes = { module = "com.svenjacobs.reveal:reveal-shapes", version.ref = "reveal" }

sqlite-bundled = { module = "androidx.sqlite:sqlite-bundled", version.ref = "sqlite" }

ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "uiBackhandler" }

xicon_pack_z_font_awesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "xicon_pack_z" }
xicon_pack_z_octicon = { module = "br.com.devsrsouza.compose.icons:octicons", version.ref = "xicon_pack_z" }
xicon_pack_z_tabler = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "xicon_pack_z" }
zoomable = { module = "net.engawapg.lib:zoomable", version.ref = "zoomable" }

[plugins] # Ordered by functionality
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }

firebase-crashlytics = { id = "com.google.firebase.crashlytics", version = "3.0.4" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google_services_version" }

jetbrains-kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }

ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
room = { id = "androidx.room", version.ref = "room" }


[bundles]
coil = [
    "coil-compose",
    "coil-compose-core",
    "coil-network-ktor2",
    "coil-network-ktor3",
    "coil-mp"
]

ktor = [
    "ktor-client-core",
    "ktor-client-content-negotiation",
    "ktor-client-auth",
    "ktor-client-logging",
    "ktor-serialization-kotlinx-json"
]
